Repository QuakeWang/storify, pull requests merged in 2025-09, with the labels that each got.

#33 feat: add support for COS storage provider in configuration and documentation
  .env.example
  Cargo.toml
  README.md
  src/config.rs
  src/storage.rs
Labels: cos

#34 bug: enhance download operations to handle malformed keys and improve path normalization
  src/storage/operations/download.rs
  src/storage/utils/path.rs
Labels: bug

#30 feat:add cat command
  README.md
  src/cli.rs
  src/error.rs
  src/storage.rs
  src/storage/constants.rs
  src/storage/operations/cat.rs
  src/storage/operations/mod.rs
  tests/behavior/main.rs
  tests/behavior/operations/cat.rs
  tests/behavior/operations/mod.rs
Labels: command cli
